### ISSUE TITLE
Wiki changes

### ISSUE THREAD

**Issue by SpyderTL** [Yoshimaster96/StarFoxDisassembly#2]
Under level format, entry 0x48 should be 5 bytes, not 6.

Also, for entry 0x2C, after the 3 byte address, there are two additional bytes that are either part of the 0x2C entry, or an entirely separate entry that is not documented.

**Comment by Yoshimaster96** [comment]
> 
> 
> Under level format, entry 0x48 should be 5 bytes, not 6.
> 
> Also, for entry 0x2C, after the 3 byte address, there are two additional bytes that are either part of the 0x2C entry, or an entirely separate entry that is not documented.

Should be fixed now.
